---
name: Generate Metric files for new Go version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update-go-versions:
    name: Update Go Versions and Generate Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Execute bash script
        run: bash update-go-version.bash

      # If there are no changes (i.e. no diff exists with the checked-out base branch),
      # no pull request will be created and the action exits silently.
      - name: Create a Pull Request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Go Collector metrics for new Go version"
          title: "chore: Update metrics for new Go version"
          branch: update-metrics-for-new-go-version
          base: main
          draft: false
          delete-branch: true
